name: Deploy
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - dev

permissions:
  actions: read
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/dev.yml
